### ISSUE TITLE
Cannot upgrade NestJS dependencies due to @fastify/static package

### ISSUE THREAD

**Issue by v-beltran** [nestjs/serve-static#1341]
### Did you read the migration guide?

- [ ] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Versions

4.0.0 -> 4.0.1

### Describe the regression

The regression is related to using Fastify with NestJS dependencies, such as `@nestjs/core`. They are pinned to version `7.0.1` for `@fastify/static` but the latest version that this package is using is pinned to `6.12.0` for `@fastify/static`.

### Minimum reproduction code

Install the latest NestJS packages with Fastify.

### Expected behavior

Should be able to install without any dependency version issues.

**Comment by micalevisk** [comment]
#1291
