### ISSUE TITLE
please pump path-to-regexp dependency (high severity vulnerabilities now)

### ISSUE THREAD

**Issue by hkjeffchan** [nestjs/serve-static#1494]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

high severity vulnerabilities reported by npm audit

### Minimum reproduction code

https://github.com/nestjs/serve-static

### Expected behavior

No vulnerabilities reported by npm audit

### Package version

4.0.2

### NestJS version

10.4.5

### Node.js version

22.8.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/serve-static/pull/1454
