### ISSUE TITLE
Can't exclude the root path

### ISSUE THREAD

**Issue by Isigiel** [nestjs/serve-static#214]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

```ts
    ServeStaticModule.forRoot({
      rootPath: frontendPath,
      exclude: ['', '/', '/events'],
    }),
```

This config still serves my files on the base path of my application, even though i excluded it. It works correctly when calling `/events`.

## Expected behavior

I'd expect no static serving when requesting `http://localhost:4200/`

## Minimal reproduction of the problem with instructions

I'm using angular to render the other routes.
```ts
@Module({
  imports: [
    AngularUniversalModule.forRoot({
      bootstrap: AppServerModule,
      viewsPath: frontendPath,
      renderPath: '*',
    }),
    ServeStaticModule.forRoot({
      rootPath: frontendPath,
      exclude: ['', '/', '/events'],
    }),
  ],
  controllers: [AppController],
  providers: [AppService],
})
```

## What is the motivation / use case for changing the behavior?

I'd like my angular app to handle the root route

**Comment by kamilmysliwiec** [comment]
This is not the intended use case for this package. Using the `ServeStaticModule` in combination with the `AngularUniversalModule` which sort of already embeds the `ServeStaticModule` behavior doesn't make too much sense. 

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
