### ISSUE TITLE
Missing 'fallthough' option

### ISSUE THREAD

**Issue by JeremyLoy** [nestjs/serve-static#331]
https://expressjs.com/en/4x/api.html#fallthrough

The `ServeStaticOptions` type when using this Plugin is missing the `fallthrough` property, which exists on`NestExpressApplication#useStaticAssets`

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this?

**Comment by Tony133** [comment]
Hi, @kamilmysliwiec

I created a pull request for this:  #372 

I hope it will go well

Tony

**Comment by marcospampi** [comment]
Is it intentional so that fallthrough will not fallthrough to the next static path? or am I doing something wrong?
