### ISSUE TITLE
Why using serve-static over useStaticAssets() for SPA?

### ISSUE THREAD

**Issue by mivoe** [nestjs/serve-static#340]
What are the benefits of serve-static?

**Comment by kamilmysliwiec** [comment]
This package is intended to minimize & simplify the boilerplate code needed for serving **SPA** from Nest. However, it doesn't ship with any additional features and isn't **required**. Using `useStaticAssets()` is completely fine and provides more control & gives more flexibility but at the same time, requires more configuration & understanding of express/fastify (depending on what you use).
