### ISSUE TITLE
serveStaticOptions: { index: false } doesn't work

### ISSUE THREAD

**Issue by tarasvakulka** [nestjs/serve-static#591]
If I set :
ServeStaticModule.forRoot({
      rootPath: path.resolve(__dirname,  'static'),
      serveStaticOptions: {
        index: false
      }
})
I still get error in console: 
ENOENT: no such file or directory, stat '/../dist/static/index.html'

"@nestjs/serve-static": "2.2.2",
"@nestjs/common": "7.6.15",
"@nestjs/config": "0.6.3",
"@nestjs/core": "7.6.15",

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
