### ISSUE TITLE
Support for nestjs v9

### ISSUE THREAD

**Issue by CatsJuice** [nestjs/serve-static#919]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I am migrating my `nestjs` project from `v8` to `v9`. The `fastify-static` dependency in the latest version of `nestjs@9` has been deprecated, and I have installed `@fastify/static`. The project throws the following error:

```
[Nest] 72982  - 2022/07/08 下午5:36:44   ERROR [PackageLoader] The "fastify-static" package is missing. Please, make sure to install this library ($ npm install fastify-static) to take advantage of ServeStaticModule.
```

I checked the source code of `@nestjs/serve-static` for the latest version(`2.2.2`) and found a dependency on `fastify-static`. Is `@nestjs/serve-static` being updated or scheduled to be updated. If so, when will I be able to use it?

### Describe the solution you'd like

Publish updates dependent on `@fastify/static`instead.

### What is the motivation / use case for changing the behavior?

Migrating nestjs from v8 to v9

**Comment by kamilmysliwiec** [comment]
Fixed in v3
